# Generated by Django 5.2.1 on 2025-12-14 22:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_membership_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='counting_mode',
            field=models.CharField(choices=[('unit', 'Unité'), ('weight', 'Poids'), ('volume', 'Volume'), ('mixed', 'Mixte')], default='unit', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.JSONField(default=accounts.models.default_service_features),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('grocery_food', 'Epicerie alimentaire'), ('bulk_food', 'Vrac'), ('bar', 'Bar'), ('kitchen', 'Cuisine / Restaurant'), ('retail_general', 'Boutique non-alimentaire'), ('pharmacy_parapharmacy', 'Pharmacie / Parapharmacie'), ('other', 'Autre')], default='other', max_length=40),
        ),
    ]
