# Generated by Django 5.2.1 on 2025-12-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_service_counting_mode_service_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('grocery', 'Grocery / Epicerie'), ('retail', 'Retail / Boutique'), ('camping_multi', 'Camping / Hôtel multi-services'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
