# Generated by Django 5.2.1 on 2025-12-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tenant_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('grocery_food', 'Epicerie alimentaire'), ('bulk_food', 'Vrac'), ('bar', 'Bar'), ('kitchen', 'Cuisine / Restaurant'), ('bakery', 'Boulangerie / Pâtisserie'), ('restaurant_dining', 'Salle / Restaurant'), ('retail_general', 'Boutique non-alimentaire'), ('pharmacy_parapharmacy', 'Pharmacie / Parapharmacie'), ('other', 'Autre')], default='other', max_length=40),
        ),
    ]
