# Generated by Django 5.2.1 on 2025-12-16 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoped_memberships', to='accounts.service'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('EXPORT', 'Export'), ('INVITE', 'Invite'), ('ROLE_CHANGE', 'Role change'), ('MEMBER_REMOVE', 'Member remove')], max_length=50)),
                ('object_type', models.CharField(blank=True, default='', max_length=50)),
                ('object_id', models.CharField(blank=True, default='', max_length=80)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='accounts_au_tenant__f910b7_idx'), models.Index(fields=['tenant', 'action'], name='accounts_au_tenant__5d7968_idx'), models.Index(fields=['user', 'created_at'], name='accounts_au_user_id_7b1069_idx')],
            },
        ),
    ]
