# Generated by Django 5.2.1 on 2025-12-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_auditlog_accounts_au_user_id_7b1069_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('grocery', 'Grocery / Epicerie'), ('retail', 'Retail / Boutique'), ('camping_multi', 'Camping / Hôtel multi-services'), ('pharmacy', 'Pharmacie / Parapharmacie'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
