# Generated by Django 5.2.1 on 2025-12-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_tenant_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active')], db_index=True, default='ACTIVE', max_length=10),
        ),
    ]
