# Generated by Django 5.2.1 on 2025-12-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_membership_activated_at_membership_invited_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='invited_at',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='status',
        ),
    ]
