# Generated by Django 5.2.1 on 2025-12-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_membership_activated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INVITED', 'Invited'), ('DISABLED', 'Disabled')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
