# Generated by Django 4.2.16 on 2025-05-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('sec', 'Sec'), ('frais', 'Frais'), ('non_perissable', 'Non périssable')], max_length=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dlc', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
