# Generated by Django 4.2.16 on 2025-05-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_month',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sec', 'Sec'), ('frais', 'Frais'), ('non_perissable', 'Non périssable'), ('portants', 'Portants'), ('articles_de_plage', 'Articles de plage')], max_length=50),
        ),
    ]
