# Generated by Django 5.2.1 on 2025-12-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_barcode'),
        ('products', '0003_service_and_no_barcode'),
    ]

    operations = [
    ]
