# Generated by Django 5.2.1 on 2025-12-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_fix_inventory_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_month',
            field=models.CharField(db_index=True, max_length=7),
        ),
    ]
