# Generated by Django 5.2.1 on 2025-12-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_unit_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='container_status',
            field=models.CharField(choices=[('SEALED', 'Non entamé'), ('OPENED', 'Entamé')], default='SEALED', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='is_packaged_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_uom',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='remaining_fraction',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='remaining_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
