# Generated by Django 5.2.1 on 2025-12-15 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tenant_business_type'),
        ('products', '0010_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LossEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField()),
                ('inventory_month', models.CharField(db_index=True, max_length=7)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit', models.CharField(choices=[('pcs', 'pcs'), ('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('ml', 'ml')], default='pcs', max_length=10)),
                ('reason', models.CharField(choices=[('breakage', 'Casse'), ('expired', 'DLC dépassée'), ('theft', 'Vol'), ('free', 'Offert'), ('mistake', 'Erreur'), ('other', 'Autre')], default='other', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='losses_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loss_events', to='products.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losses', to='accounts.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losses', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['tenant', 'service', 'inventory_month'], name='products_lo_tenant__6f8bc9_idx'), models.Index(fields=['tenant', 'service', 'occurred_at'], name='products_lo_tenant__749b72_idx')],
            },
        ),
    ]
