# Generated by Django 5.2.1 on 2025-12-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_lossevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cold_chain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_type',
            field=models.CharField(blank=True, choices=[('24h', '24h'), ('DLC', 'DLC'), ('DDM', 'DDM'), ('none', 'Aucune')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fabrication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_stupefiant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='lot_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_role',
            field=models.CharField(blank=True, choices=[('raw_material', 'Matière première'), ('finished_product', 'Produit fini'), ('homemade_prep', 'Préparation maison')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
