# Generated by Django 5.2.1 on 2025-12-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_invitation'),
        ('products', '0012_product_cold_chain_product_expiry_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_barcode_per_month_tenant_service',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_internal_sku_per_month_tenant_service',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'service', 'inventory_month'], name='products_pr_tenant__794718_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'service', 'created_at'], name='products_pr_tenant__98934a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'service', 'barcode'], name='products_pr_tenant__b62dba_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'service', 'internal_sku'], name='products_pr_tenant__4c4e61_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False), models.Q(('barcode', ''), _negated=True)), fields=('tenant', 'service', 'barcode', 'inventory_month'), name='uniq_barcode_per_month_tenant_service_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_sku__isnull', False), models.Q(('internal_sku', ''), _negated=True)), fields=('tenant', 'service', 'internal_sku', 'inventory_month'), name='uniq_sku_per_month_tenant_service_nonempty'),
        ),
    ]
