# Generated by Django 5.2.1 on 2025-12-28 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_service_sku_sequence'),
        ('products', '0017_product_archives_receipts_labels'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='uniq_barcode_per_month_tenant_service_nonempty',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='uniq_sku_per_month_tenant_service_nonempty',
        ),
        migrations.AlterField(
            model_name='productmergelog',
            name='master_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_master', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productmergelog',
            name='merged_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_merged', to='products.product'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False), models.Q(('barcode', ''), _negated=True), ('is_archived', False)), fields=('tenant', 'service', 'barcode', 'inventory_month'), name='uniq_barcode_per_month_tenant_service_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_sku__isnull', False), models.Q(('internal_sku', ''), _negated=True), ('is_archived', False)), fields=('tenant', 'service', 'internal_sku', 'inventory_month'), name='uniq_sku_per_month_tenant_service_nonempty'),
        ),
    ]
