# Generated by Django 5.2.1 on 2026-01-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pospayment',
            new_name='pos_pospaym_ticket__7bd4f1_idx',
            old_name='pos_payment_ticket__f2e2a8_idx',
        ),
        migrations.RenameIndex(
            model_name='pospayment',
            new_name='pos_pospaym_method_17a858_idx',
            old_name='pos_payment_method__2a2b48_idx',
        ),
        migrations.RenameIndex(
            model_name='posticket',
            new_name='pos_postick_tenant__3f1bd2_idx',
            old_name='pos_postick_tenant__e9c15a_idx',
        ),
        migrations.RenameIndex(
            model_name='posticket',
            new_name='pos_postick_tenant__3d64d4_idx',
            old_name='pos_postick_tenant__8c9c26_idx',
        ),
        migrations.RenameIndex(
            model_name='posticketline',
            new_name='pos_postick_ticket__42effc_idx',
            old_name='pos_postick_ticket__1702f2_idx',
        ),
    ]
