# Generated by Django 5.2.1 on 2026-01-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_pos_cash_session_and_ticket_events'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='poscashsession',
            new_name='pos_poscash_tenant__97503a_idx',
            old_name='pos_poscas_tenant__9a4660_idx',
        ),
        migrations.RenameIndex(
            model_name='poscashsession',
            new_name='pos_poscash_tenant__fac6a5_idx',
            old_name='pos_poscas_tenant__d8a5fd_idx',
        ),
        migrations.RenameIndex(
            model_name='posticketevent',
            new_name='pos_postick_ticket__3548f6_idx',
            old_name='pos_postic_ticket__7f6a5a_idx',
        ),
    ]
