# Generated by Django 5.2.1 on 2026-01-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kds', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kdstable',
            new_name='kds_kdstabl_tenant__8edad4_idx',
            old_name='kds_kdstab_tenant__0e61f0_idx',
        ),
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='kds_menuite_tenant__28307e_idx',
            old_name='kds_menuit_tenant__a8dd3c_idx',
        ),
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='kds_menuite_tenant__b254fa_idx',
            old_name='kds_menuit_tenant__9eb45f_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='kds_order_tenant__cf89e0_idx',
            old_name='kds_order_tenant__32f2cc_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='kds_order_tenant__6760d9_idx',
            old_name='kds_order_tenant__5a55d0_idx',
        ),
        migrations.RenameIndex(
            model_name='orderline',
            new_name='kds_orderli_order_i_bc7ccd_idx',
            old_name='kds_orderli_order_i_796461_idx',
        ),
        migrations.RenameIndex(
            model_name='recipeitem',
            new_name='kds_recipei_menu_it_e62fed_idx',
            old_name='kds_recipei_menu_it_2bc9a9_idx',
        ),
        migrations.RenameIndex(
            model_name='stockconsumption',
            new_name='kds_stockco_tenant__dfd870_idx',
            old_name='kds_stockc_tenant__1c6b86_idx',
        ),
        migrations.RenameIndex(
            model_name='stockconsumption',
            new_name='kds_stockco_product_1bb355_idx',
            old_name='kds_stockc_product_a9b27d_idx',
        ),
        migrations.RenameIndex(
            model_name='wasteevent',
            new_name='kds_wasteev_tenant__c4438e_idx',
            old_name='kds_wastee_tenant__4fa7b4_idx',
        ),
    ]
