# Generated by Django 5.2.1 on 2026-01-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='admindailymetric',
            new_name='admin_dashb_key_349696_idx',
            old_name='admin_dash_key_date_idx',
        ),
    ]
