# Generated by Django 5.2.1 on 2026-01-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0002_adminvisitevent"),
        ("admin_dashboard", "0002_rename_admin_dash_key_date_idx_admin_dashb_key_349696_idx"),
    ]

    operations = []
