# Generated by Django 5.2.1 on 2026-01-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_merge_20260109_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindailymetric',
            name='key',
            field=models.CharField(choices=[('visit_root', 'Visit / (legacy)'), ('visit_landing', 'Visit landing'), ('visit_pos', 'Visit /pos'), ('visit_kds', 'Visit /kds')], max_length=50),
        ),
    ]
